name: Simple Echo Workflow

on:
  push:
    branches:
      - main

jobs:
  echo_message:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "Hello from GitHub Actions!"
