name: Triggered Workflow

on:
  repository_dispatch:
    types:
      - trigger-workflow-event

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
        
    
       - name: Print Message
         run: echo "Hello from GitHub Actions!"
